theme: just-the-docs
aux_links:
  "Ask your questions on Discord":
    - "https://discord.gg/Zx37vEkzzB"
color_scheme: dustup
callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: yellow
  tip:
    title: Tip
    color: blue
